spring:
  mail:
    host: smtp.xxx.com.cn # 邮箱服务器地址
    username: xxxxx@xxxx.com.cn # 用户名
    password: 123456      # 密码
    default-encoding: UTF-8

mail:
  fromMail:
    addr: xxxx@xxxx.com.cn  # 以谁来发送邮件
